# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChainReactWorkshop' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ChainReactWorkshop
  pod 'TensorFlow-experimental'
  
  target 'ChainReactWorkshopTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ChainReactWorkshop-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ChainReactWorkshop-tvOS

  target 'ChainReactWorkshop-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
